// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Telemetry.proto

package Telemetry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Provisioning_ReadDefT_RegLengthT int32

const (
	Provisioning_ReadDefT_RL16 Provisioning_ReadDefT_RegLengthT = 0
	Provisioning_ReadDefT_RL8  Provisioning_ReadDefT_RegLengthT = 1
)

var Provisioning_ReadDefT_RegLengthT_name = map[int32]string{
	0: "RL16",
	1: "RL8",
}

var Provisioning_ReadDefT_RegLengthT_value = map[string]int32{
	"RL16": 0,
	"RL8":  1,
}

func (x Provisioning_ReadDefT_RegLengthT) String() string {
	return proto.EnumName(Provisioning_ReadDefT_RegLengthT_name, int32(x))
}

func (Provisioning_ReadDefT_RegLengthT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{2, 0, 0}
}

type Request_ActionT int32

const (
	//*
	// Request microcontroller reboot.
	Request_REBOOT Request_ActionT = 0
	//*
	// Request manual schedule execution and Payload frame(s).
	Request_POLL Request_ActionT = 1
	//*
	// Request manual Registration frame.
	Request_HEARTBEAT Request_ActionT = 2
)

var Request_ActionT_name = map[int32]string{
	0: "REBOOT",
	1: "POLL",
	2: "HEARTBEAT",
}

var Request_ActionT_value = map[string]int32{
	"REBOOT":    0,
	"POLL":      1,
	"HEARTBEAT": 2,
}

func (x Request_ActionT) String() string {
	return proto.EnumName(Request_ActionT_name, int32(x))
}

func (Request_ActionT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{4, 0}
}

//*
// MQTT binary payload.
type Telemetry struct {
	// Types that are valid to be assigned to Message:
	//	*Telemetry_Registration
	//	*Telemetry_Provisioning
	//	*Telemetry_Payload
	//	*Telemetry_Request
	Message              isTelemetry_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Telemetry) Reset()         { *m = Telemetry{} }
func (m *Telemetry) String() string { return proto.CompactTextString(m) }
func (*Telemetry) ProtoMessage()    {}
func (*Telemetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{0}
}

func (m *Telemetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telemetry.Unmarshal(m, b)
}
func (m *Telemetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telemetry.Marshal(b, m, deterministic)
}
func (m *Telemetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telemetry.Merge(m, src)
}
func (m *Telemetry) XXX_Size() int {
	return xxx_messageInfo_Telemetry.Size(m)
}
func (m *Telemetry) XXX_DiscardUnknown() {
	xxx_messageInfo_Telemetry.DiscardUnknown(m)
}

var xxx_messageInfo_Telemetry proto.InternalMessageInfo

type isTelemetry_Message interface {
	isTelemetry_Message()
}

type Telemetry_Registration struct {
	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type Telemetry_Provisioning struct {
	Provisioning *Provisioning `protobuf:"bytes,2,opt,name=provisioning,proto3,oneof"`
}

type Telemetry_Payload struct {
	Payload *Payload `protobuf:"bytes,3,opt,name=payload,proto3,oneof"`
}

type Telemetry_Request struct {
	Request *Request `protobuf:"bytes,4,opt,name=request,proto3,oneof"`
}

func (*Telemetry_Registration) isTelemetry_Message() {}

func (*Telemetry_Provisioning) isTelemetry_Message() {}

func (*Telemetry_Payload) isTelemetry_Message() {}

func (*Telemetry_Request) isTelemetry_Message() {}

func (m *Telemetry) GetMessage() isTelemetry_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Telemetry) GetRegistration() *Registration {
	if x, ok := m.GetMessage().(*Telemetry_Registration); ok {
		return x.Registration
	}
	return nil
}

func (m *Telemetry) GetProvisioning() *Provisioning {
	if x, ok := m.GetMessage().(*Telemetry_Provisioning); ok {
		return x.Provisioning
	}
	return nil
}

func (m *Telemetry) GetPayload() *Payload {
	if x, ok := m.GetMessage().(*Telemetry_Payload); ok {
		return x.Payload
	}
	return nil
}

func (m *Telemetry) GetRequest() *Request {
	if x, ok := m.GetMessage().(*Telemetry_Request); ok {
		return x.Request
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Telemetry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Telemetry_Registration)(nil),
		(*Telemetry_Provisioning)(nil),
		(*Telemetry_Payload)(nil),
		(*Telemetry_Request)(nil),
	}
}

//*
// Registration frame (microcontroller -> backend).
//
// Conditions:
//  - MQTT connection established, re-established
//  - Peripheral connected, disconnected
type Registration struct {
	//*
	// Firmware version identifier.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	//*
	// Microcontroller unique identifier (MAC address).
	Uuid []byte `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	//*
	// Microcontroller IP address.
	Ip []byte `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	//*
	// List of connected peripherals.
	Peripherals          []*Registration_PeripheralT `protobuf:"bytes,4,rep,name=peripherals,proto3" json:"peripherals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Registration) Reset()         { *m = Registration{} }
func (m *Registration) String() string { return proto.CompactTextString(m) }
func (*Registration) ProtoMessage()    {}
func (*Registration) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{1}
}

func (m *Registration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registration.Unmarshal(m, b)
}
func (m *Registration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registration.Marshal(b, m, deterministic)
}
func (m *Registration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registration.Merge(m, src)
}
func (m *Registration) XXX_Size() int {
	return xxx_messageInfo_Registration.Size(m)
}
func (m *Registration) XXX_DiscardUnknown() {
	xxx_messageInfo_Registration.DiscardUnknown(m)
}

var xxx_messageInfo_Registration proto.InternalMessageInfo

func (m *Registration) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Registration) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *Registration) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *Registration) GetPeripherals() []*Registration_PeripheralT {
	if m != nil {
		return m.Peripherals
	}
	return nil
}

type Registration_PeripheralT struct {
	BusId                uint32   `protobuf:"varint,1,opt,name=busId,proto3" json:"busId,omitempty"`
	BusAddr              uint32   `protobuf:"varint,2,opt,name=busAddr,proto3" json:"busAddr,omitempty"`
	GeneralCallResp      []byte   `protobuf:"bytes,3,opt,name=generalCallResp,proto3" json:"generalCallResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Registration_PeripheralT) Reset()         { *m = Registration_PeripheralT{} }
func (m *Registration_PeripheralT) String() string { return proto.CompactTextString(m) }
func (*Registration_PeripheralT) ProtoMessage()    {}
func (*Registration_PeripheralT) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{1, 0}
}

func (m *Registration_PeripheralT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registration_PeripheralT.Unmarshal(m, b)
}
func (m *Registration_PeripheralT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registration_PeripheralT.Marshal(b, m, deterministic)
}
func (m *Registration_PeripheralT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registration_PeripheralT.Merge(m, src)
}
func (m *Registration_PeripheralT) XXX_Size() int {
	return xxx_messageInfo_Registration_PeripheralT.Size(m)
}
func (m *Registration_PeripheralT) XXX_DiscardUnknown() {
	xxx_messageInfo_Registration_PeripheralT.DiscardUnknown(m)
}

var xxx_messageInfo_Registration_PeripheralT proto.InternalMessageInfo

func (m *Registration_PeripheralT) GetBusId() uint32 {
	if m != nil {
		return m.BusId
	}
	return 0
}

func (m *Registration_PeripheralT) GetBusAddr() uint32 {
	if m != nil {
		return m.BusAddr
	}
	return 0
}

func (m *Registration_PeripheralT) GetGeneralCallResp() []byte {
	if m != nil {
		return m.GeneralCallResp
	}
	return nil
}

//*
// Provisioning frame (backend -> microcontroller).
//
// Conditions:
//  - Received Registration frame from microcontroller.
//  - Received new read definitions from corresponding peripheral controller.
type Provisioning struct {
	//*
	// Default bus address for peripheral.
	BusAddr uint32 `protobuf:"varint,1,opt,name=busAddr,proto3" json:"busAddr,omitempty"`
	//*
	// Display name of peripheral processor.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//
	// Peripheral read definitions.
	ReadDefinitions      []*Provisioning_ReadDefT `protobuf:"bytes,3,rep,name=readDefinitions,proto3" json:"readDefinitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Provisioning) Reset()         { *m = Provisioning{} }
func (m *Provisioning) String() string { return proto.CompactTextString(m) }
func (*Provisioning) ProtoMessage()    {}
func (*Provisioning) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{2}
}

func (m *Provisioning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provisioning.Unmarshal(m, b)
}
func (m *Provisioning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provisioning.Marshal(b, m, deterministic)
}
func (m *Provisioning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provisioning.Merge(m, src)
}
func (m *Provisioning) XXX_Size() int {
	return xxx_messageInfo_Provisioning.Size(m)
}
func (m *Provisioning) XXX_DiscardUnknown() {
	xxx_messageInfo_Provisioning.DiscardUnknown(m)
}

var xxx_messageInfo_Provisioning proto.InternalMessageInfo

func (m *Provisioning) GetBusAddr() uint32 {
	if m != nil {
		return m.BusAddr
	}
	return 0
}

func (m *Provisioning) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provisioning) GetReadDefinitions() []*Provisioning_ReadDefT {
	if m != nil {
		return m.ReadDefinitions
	}
	return nil
}

type Provisioning_ReadDefT struct {
	//*
	// An arbitrary ID for external reference. This does not relate to the
	// hardware or any application logic in the I2CRuntime. This is used
	// externally to track read definitions.
	DefinitionId uint32 `protobuf:"varint,1,opt,name=definitionId,proto3" json:"definitionId,omitempty"`
	//*
	// Some peripherals have 16-bit register IDs and some have 8-bit register
	// IDs.
	RegisterIdLength Provisioning_ReadDefT_RegLengthT `protobuf:"varint,2,opt,name=registerIdLength,proto3,enum=Provisioning_ReadDefT_RegLengthT" json:"registerIdLength,omitempty"`
	//*
	// Data is read on this output from a contiguous block of register IDs.
	// e.g., 0x80 to 0xFF. This is the first register ID of the block.
	RegisterId uint32 `protobuf:"varint,3,opt,name=registerId,proto3" json:"registerId,omitempty"`
	//*
	// Data is read on this output from a contiguous block of register IDs.
	// e.g., 0x80 to 0xFF. This defines the number of register IDs in the block.
	// This is essentially how many times the loop will read bytes at a register
	// and then advance to the next register. For many peripherals this value is
	// simple 1 (i.e., there is no need to advance).
	RegisterBlockLength uint32 `protobuf:"varint,4,opt,name=registerBlockLength,proto3" json:"registerBlockLength,omitempty"`
	//*
	// The number of bytes that will be read at each register ID in the
	// contiguous block. This means that the total number of bytes retrieved
	// from one ReadDefinition instance is:
	//
	//     numBytesPerRegister * registerBlockLength
	NumBytesPerRegister uint32 `protobuf:"varint,5,opt,name=numBytesPerRegister,proto3" json:"numBytesPerRegister,omitempty"`
	//*
	// How many milliseconds between reading all bytes from the block of
	// registers?
	ReadPeriod           uint32   `protobuf:"varint,6,opt,name=readPeriod,proto3" json:"readPeriod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Provisioning_ReadDefT) Reset()         { *m = Provisioning_ReadDefT{} }
func (m *Provisioning_ReadDefT) String() string { return proto.CompactTextString(m) }
func (*Provisioning_ReadDefT) ProtoMessage()    {}
func (*Provisioning_ReadDefT) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{2, 0}
}

func (m *Provisioning_ReadDefT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provisioning_ReadDefT.Unmarshal(m, b)
}
func (m *Provisioning_ReadDefT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provisioning_ReadDefT.Marshal(b, m, deterministic)
}
func (m *Provisioning_ReadDefT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provisioning_ReadDefT.Merge(m, src)
}
func (m *Provisioning_ReadDefT) XXX_Size() int {
	return xxx_messageInfo_Provisioning_ReadDefT.Size(m)
}
func (m *Provisioning_ReadDefT) XXX_DiscardUnknown() {
	xxx_messageInfo_Provisioning_ReadDefT.DiscardUnknown(m)
}

var xxx_messageInfo_Provisioning_ReadDefT proto.InternalMessageInfo

func (m *Provisioning_ReadDefT) GetDefinitionId() uint32 {
	if m != nil {
		return m.DefinitionId
	}
	return 0
}

func (m *Provisioning_ReadDefT) GetRegisterIdLength() Provisioning_ReadDefT_RegLengthT {
	if m != nil {
		return m.RegisterIdLength
	}
	return Provisioning_ReadDefT_RL16
}

func (m *Provisioning_ReadDefT) GetRegisterId() uint32 {
	if m != nil {
		return m.RegisterId
	}
	return 0
}

func (m *Provisioning_ReadDefT) GetRegisterBlockLength() uint32 {
	if m != nil {
		return m.RegisterBlockLength
	}
	return 0
}

func (m *Provisioning_ReadDefT) GetNumBytesPerRegister() uint32 {
	if m != nil {
		return m.NumBytesPerRegister
	}
	return 0
}

func (m *Provisioning_ReadDefT) GetReadPeriod() uint32 {
	if m != nil {
		return m.ReadPeriod
	}
	return 0
}

//*
// Payload frame (microcontroller -> backend).
//
// Conditions:
//  - Data collected from peripheral.
type Payload struct {
	//*
	// I2C bus ID payload was collected from.
	BusId uint32 `protobuf:"varint,1,opt,name=busId,proto3" json:"busId,omitempty"`
	//*
	// I2C bus address payload was collected from.
	BusAddr uint32 `protobuf:"varint,2,opt,name=busAddr,proto3" json:"busAddr,omitempty"`
	//*
	// Payload collection definition identifier, matching ReadDef_t.
	DefinitionId uint32 `protobuf:"varint,3,opt,name=definitionId,proto3" json:"definitionId,omitempty"`
	//*
	// Contents of peripheral read.
	Buff                 []byte   `protobuf:"bytes,4,opt,name=buff,proto3" json:"buff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{3}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetBusId() uint32 {
	if m != nil {
		return m.BusId
	}
	return 0
}

func (m *Payload) GetBusAddr() uint32 {
	if m != nil {
		return m.BusAddr
	}
	return 0
}

func (m *Payload) GetDefinitionId() uint32 {
	if m != nil {
		return m.DefinitionId
	}
	return 0
}

func (m *Payload) GetBuff() []byte {
	if m != nil {
		return m.Buff
	}
	return nil
}

//*
// Request frame (backend -> microcontroller).
//
// Conditions:
//  - Request microcontroller to reboot.
//  - Request microcontroller to poll peripherals, send Payload frame(s).
//  - Request microcontroller to send heartbeat (Registration frame).
type Request struct {
	Action               Request_ActionT `protobuf:"varint,1,opt,name=action,proto3,enum=Request_ActionT" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAction() Request_ActionT {
	if m != nil {
		return m.Action
	}
	return Request_REBOOT
}

func init() {
	proto.RegisterEnum("Provisioning_ReadDefT_RegLengthT", Provisioning_ReadDefT_RegLengthT_name, Provisioning_ReadDefT_RegLengthT_value)
	proto.RegisterEnum("Request_ActionT", Request_ActionT_name, Request_ActionT_value)
	proto.RegisterType((*Telemetry)(nil), "Telemetry")
	proto.RegisterType((*Registration)(nil), "Registration")
	proto.RegisterType((*Registration_PeripheralT)(nil), "Registration.Peripheral_t")
	proto.RegisterType((*Provisioning)(nil), "Provisioning")
	proto.RegisterType((*Provisioning_ReadDefT)(nil), "Provisioning.ReadDef_t")
	proto.RegisterType((*Payload)(nil), "Payload")
	proto.RegisterType((*Request)(nil), "Request")
}

func init() { proto.RegisterFile("Telemetry.proto", fileDescriptor_93f6e686c665f83a) }

var fileDescriptor_93f6e686c665f83a = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0xaf, 0xd2, 0x40,
	0x10, 0xc7, 0x29, 0xed, 0xa3, 0x8f, 0xa1, 0x40, 0x5d, 0x4d, 0x6c, 0x38, 0x18, 0x52, 0x3d, 0xe0,
	0xa5, 0x2a, 0x2f, 0x31, 0x1e, 0xbc, 0x80, 0x92, 0xf0, 0x12, 0x12, 0xc8, 0x84, 0x3b, 0x29, 0xaf,
	0x0b, 0x34, 0x96, 0xb6, 0x6f, 0x77, 0xfb, 0x12, 0xfe, 0x41, 0xe3, 0xc1, 0x3f, 0xc7, 0x3f, 0xc0,
	0xec, 0xf6, 0x87, 0x05, 0xf1, 0xe0, 0x6d, 0xe7, 0x3b, 0x9f, 0xe9, 0x7e, 0x67, 0xda, 0x29, 0xf4,
	0xd7, 0x34, 0xa2, 0x47, 0x2a, 0xd8, 0xc9, 0x4b, 0x59, 0x22, 0x12, 0xf7, 0xa7, 0x06, 0xed, 0x4a,
	0x23, 0x77, 0x60, 0x31, 0xba, 0x0f, 0xb9, 0x60, 0xbe, 0x08, 0x93, 0xd8, 0xd1, 0x86, 0xda, 0xa8,
	0x33, 0xee, 0x7a, 0x58, 0x13, 0xe7, 0x0d, 0x3c, 0x83, 0x64, 0x51, 0xca, 0x92, 0xa7, 0x90, 0x87,
	0x49, 0x1c, 0xc6, 0x7b, 0xa7, 0x59, 0x14, 0xad, 0x6a, 0xa2, 0x2c, 0xaa, 0x43, 0xe4, 0x0d, 0x98,
	0xa9, 0x7f, 0x8a, 0x12, 0x3f, 0x70, 0x74, 0xc5, 0xdf, 0x7a, 0xab, 0x3c, 0x9e, 0x37, 0xb0, 0x4c,
	0x49, 0x8a, 0xd1, 0xc7, 0x8c, 0x72, 0xe1, 0x18, 0x05, 0x85, 0x79, 0x2c, 0xa9, 0x22, 0x35, 0x6d,
	0x83, 0x79, 0xa4, 0x9c, 0xfb, 0x7b, 0xea, 0xfe, 0xd2, 0xc0, 0xaa, 0x9b, 0x25, 0x0e, 0x98, 0x4f,
	0x94, 0xf1, 0xb2, 0x99, 0x2e, 0x96, 0x21, 0x21, 0x60, 0x64, 0x59, 0x18, 0x28, 0xbb, 0x16, 0xaa,
	0x33, 0xe9, 0x41, 0x33, 0x4c, 0x95, 0x21, 0x0b, 0x9b, 0x61, 0x4a, 0x3e, 0x43, 0x27, 0xa5, 0x2c,
	0x4c, 0x0f, 0x94, 0xf9, 0x11, 0x77, 0x8c, 0xa1, 0x3e, 0xea, 0x8c, 0x07, 0x67, 0xe3, 0xf0, 0x56,
	0x15, 0xb0, 0x11, 0x58, 0xc7, 0x07, 0x07, 0xb0, 0xea, 0x49, 0xf2, 0x02, 0x6e, 0xb6, 0x19, 0xbf,
	0x0f, 0x0a, 0x27, 0x79, 0x20, 0x1d, 0x6e, 0x33, 0x3e, 0x09, 0x02, 0xa6, 0xac, 0x74, 0xb1, 0x0c,
	0xc9, 0x08, 0xfa, 0x7b, 0x1a, 0xcb, 0xe2, 0x2f, 0x7e, 0x14, 0x21, 0xe5, 0xa5, 0xb5, 0x4b, 0xd9,
	0xfd, 0xa1, 0x83, 0x55, 0x1f, 0x77, 0xfd, 0xa1, 0xda, 0xf9, 0x43, 0x09, 0x18, 0xb1, 0x7f, 0xa4,
	0xea, 0xae, 0x36, 0xaa, 0x33, 0x99, 0x40, 0x9f, 0x51, 0x3f, 0xf8, 0x4a, 0x77, 0x61, 0x1c, 0xca,
	0xa6, 0xb8, 0xa3, 0xab, 0x56, 0x5f, 0x9e, 0xbd, 0x44, 0x0f, 0x73, 0x68, 0x23, 0xf0, 0x92, 0x1f,
	0x7c, 0x6f, 0x42, 0xbb, 0x4a, 0x13, 0x17, 0xac, 0xa0, 0x4a, 0x56, 0x0d, 0x9f, 0x69, 0x64, 0x09,
	0x76, 0xfe, 0x19, 0x51, 0x76, 0x1f, 0x2c, 0x68, 0xbc, 0x17, 0x07, 0x65, 0xaa, 0x37, 0x7e, 0xfd,
	0x8f, 0x5b, 0xe5, 0xdc, 0x73, 0x70, 0x23, 0xf0, 0xaf, 0x62, 0xf2, 0x0a, 0xe0, 0x8f, 0xa6, 0x26,
	0xd5, 0xc5, 0x9a, 0x42, 0xde, 0xc3, 0xf3, 0x32, 0x9a, 0x46, 0xc9, 0xc3, 0xb7, 0xe2, 0x4e, 0x43,
	0x81, 0xd7, 0x52, 0xb2, 0x22, 0xce, 0x8e, 0xd3, 0x93, 0xa0, 0x7c, 0x45, 0x19, 0x16, 0x84, 0x73,
	0x93, 0x57, 0x5c, 0x49, 0xe5, 0x1e, 0xfc, 0x40, 0xbe, 0xf6, 0x24, 0x70, 0x5a, 0xa5, 0x87, 0x52,
	0x71, 0x87, 0xd0, 0xa9, 0x35, 0x41, 0x6e, 0xc1, 0xc0, 0xc5, 0x87, 0x8f, 0x76, 0x83, 0x98, 0xa0,
	0xe3, 0xe2, 0x93, 0xad, 0xb9, 0x8f, 0x60, 0x16, 0x8b, 0xf0, 0xdf, 0xdf, 0xcb, 0xe5, 0xd4, 0xf5,
	0x2b, 0x53, 0x27, 0x60, 0x6c, 0xb3, 0xdd, 0x4e, 0x75, 0x6d, 0xa1, 0x3a, 0xbb, 0x14, 0xcc, 0x62,
	0xab, 0xc8, 0x5b, 0x68, 0xf9, 0x0f, 0xd5, 0xea, 0xf7, 0xc6, 0xcf, 0xca, 0x7d, 0xf3, 0x26, 0x4a,
	0xde, 0x08, 0x2c, 0x00, 0xf7, 0x1d, 0xdc, 0x96, 0x1a, 0x01, 0x68, 0xe1, 0x6c, 0xba, 0x5c, 0xae,
	0xed, 0x86, 0xec, 0x69, 0xb5, 0x5c, 0x2c, 0x6c, 0x8d, 0x74, 0xa1, 0x3d, 0x9f, 0x4d, 0x70, 0x3d,
	0x9d, 0x4d, 0xd6, 0x76, 0x73, 0xdb, 0x52, 0x7f, 0x9c, 0xbb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x83, 0x37, 0x59, 0xb4, 0x84, 0x04, 0x00, 0x00,
}
