/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.5 at Fri Feb  7 20:51:37 2020. */

#include "telemetry.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Telemetry_fields[5] = {
    PB_ONEOF_FIELD(message,   1, MESSAGE , ONEOF, STATIC  , FIRST, Telemetry, registration, registration, &Registration_fields),
    PB_ONEOF_FIELD(message,   2, MESSAGE , ONEOF, STATIC  , UNION, Telemetry, provisioning, provisioning, &Provisioning_fields),
    PB_ONEOF_FIELD(message,   3, MESSAGE , ONEOF, STATIC  , UNION, Telemetry, payload, payload, &Payload_fields),
    PB_ONEOF_FIELD(message,   4, MESSAGE , ONEOF, STATIC  , UNION, Telemetry, request, request, &Request_fields),
    PB_LAST_FIELD
};

const pb_field_t Registration_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Registration, version, version, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, Registration, uuid, version, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, Registration, ipv4, uuid, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, Registration, ipv6, ipv4, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, CALLBACK, OTHER, Registration, peripherals, ipv6, &Registration_Peripheral_fields),
    PB_LAST_FIELD
};

const pb_field_t Registration_Peripheral_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Registration_Peripheral, busId, busId, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Registration_Peripheral, busAddr, busId, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, Registration_Peripheral, generalCallResp, busAddr, 0),
    PB_LAST_FIELD
};

const pb_field_t Provisioning_fields[4] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Provisioning, busAddr, busAddr, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, Provisioning, name, busAddr, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, Provisioning, readDefinitions, name, &Provisioning_ReadDef_fields),
    PB_LAST_FIELD
};

const pb_field_t Provisioning_ReadDef_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Provisioning_ReadDef, definitionId, definitionId, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, Provisioning_ReadDef, registerIdLength, definitionId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, Provisioning_ReadDef, registerId, registerIdLength, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, Provisioning_ReadDef, registerBlockLength, registerId, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, Provisioning_ReadDef, numBytesPerRegister, registerBlockLength, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, Provisioning_ReadDef, readPeriod, numBytesPerRegister, 0),
    PB_LAST_FIELD
};

const pb_field_t Payload_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Payload, busId, busId, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Payload, busAddr, busId, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, Payload, definitionId, busAddr, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, Payload, data, definitionId, 0),
    PB_LAST_FIELD
};

const pb_field_t Request_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Request, action, action, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Telemetry, message.registration) < 65536 && pb_membersize(Telemetry, message.provisioning) < 65536 && pb_membersize(Telemetry, message.payload) < 65536 && pb_membersize(Telemetry, message.request) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Telemetry_Registration_Registration_Peripheral_Provisioning_Provisioning_ReadDef_Payload_Request)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Telemetry, message.registration) < 256 && pb_membersize(Telemetry, message.provisioning) < 256 && pb_membersize(Telemetry, message.payload) < 256 && pb_membersize(Telemetry, message.request) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Telemetry_Registration_Registration_Peripheral_Provisioning_Provisioning_ReadDef_Payload_Request)
#endif


/* @@protoc_insertion_point(eof) */
