/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Fri Sep 27 15:18:45 2019. */

#ifndef PB_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Telemetry_Type {
    Telemetry_Type_ZERO = 0,
    Telemetry_Type_RX_HELLO = 1,
    Telemetry_Type_TX_HELLO = 2,
    Telemetry_Type_RX_ACTION = 3
} Telemetry_Type;
#define _Telemetry_Type_MIN Telemetry_Type_ZERO
#define _Telemetry_Type_MAX Telemetry_Type_RX_ACTION
#define _Telemetry_Type_ARRAYSIZE ((Telemetry_Type)(Telemetry_Type_RX_ACTION+1))

typedef enum _MsgAction_Action {
    MsgAction_Action_DIGITAL_LOW = 0,
    MsgAction_Action_DIGITAL_HIGH = 1
} MsgAction_Action;
#define _MsgAction_Action_MIN MsgAction_Action_DIGITAL_LOW
#define _MsgAction_Action_MAX MsgAction_Action_DIGITAL_HIGH
#define _MsgAction_Action_ARRAYSIZE ((MsgAction_Action)(MsgAction_Action_DIGITAL_HIGH+1))

/* Struct definitions */
typedef struct _MsgAction {
    MsgAction_Action type;
    uint32_t pin;
/* @@protoc_insertion_point(struct:MsgAction) */
} MsgAction;

typedef struct _MsgHello {
    char ip[16];
    uint32_t version;
/* @@protoc_insertion_point(struct:MsgHello) */
} MsgHello;

typedef struct _Telemetry {
    Telemetry_Type type;
    MsgHello hello;
    MsgAction action;
/* @@protoc_insertion_point(struct:Telemetry) */
} Telemetry;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Telemetry_init_default                   {_Telemetry_Type_MIN, MsgHello_init_default, MsgAction_init_default}
#define MsgHello_init_default                    {"", 0}
#define MsgAction_init_default                   {_MsgAction_Action_MIN, 0}
#define Telemetry_init_zero                      {_Telemetry_Type_MIN, MsgHello_init_zero, MsgAction_init_zero}
#define MsgHello_init_zero                       {"", 0}
#define MsgAction_init_zero                      {_MsgAction_Action_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MsgAction_type_tag                       1
#define MsgAction_pin_tag                        2
#define MsgHello_ip_tag                          1
#define MsgHello_version_tag                     2
#define Telemetry_type_tag                       1
#define Telemetry_hello_tag                      2
#define Telemetry_action_tag                     3

/* Struct field encoding specification for nanopb */
extern const pb_field_t Telemetry_fields[4];
extern const pb_field_t MsgHello_fields[3];
extern const pb_field_t MsgAction_fields[3];

/* Maximum encoded size of messages (where known) */
#define Telemetry_size                           38
#define MsgHello_size                            24
#define MsgAction_size                           8

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TELEMETRY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
