// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Telemetry.proto

package Telemetry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Telemetry_Type int32

const (
	Telemetry_ZERO      Telemetry_Type = 0
	Telemetry_RX_HELLO  Telemetry_Type = 1
	Telemetry_TX_HELLO  Telemetry_Type = 2
	Telemetry_RX_ACTION Telemetry_Type = 3
)

var Telemetry_Type_name = map[int32]string{
	0: "ZERO",
	1: "RX_HELLO",
	2: "TX_HELLO",
	3: "RX_ACTION",
}

var Telemetry_Type_value = map[string]int32{
	"ZERO":      0,
	"RX_HELLO":  1,
	"TX_HELLO":  2,
	"RX_ACTION": 3,
}

func (x Telemetry_Type) String() string {
	return proto.EnumName(Telemetry_Type_name, int32(x))
}

func (Telemetry_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{0, 0}
}

type MsgAction_Action int32

const (
	MsgAction_DIGITAL_LOW  MsgAction_Action = 0
	MsgAction_DIGITAL_HIGH MsgAction_Action = 1
)

var MsgAction_Action_name = map[int32]string{
	0: "DIGITAL_LOW",
	1: "DIGITAL_HIGH",
}

var MsgAction_Action_value = map[string]int32{
	"DIGITAL_LOW":  0,
	"DIGITAL_HIGH": 1,
}

func (x MsgAction_Action) String() string {
	return proto.EnumName(MsgAction_Action_name, int32(x))
}

func (MsgAction_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{2, 0}
}

type Telemetry struct {
	// message type
	Type Telemetry_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Telemetry_Type" json:"type,omitempty"`
	// Payload (send at most one in message)
	Hello                *MsgHello  `protobuf:"bytes,2,opt,name=hello,proto3" json:"hello,omitempty"`
	Action               *MsgAction `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Telemetry) Reset()         { *m = Telemetry{} }
func (m *Telemetry) String() string { return proto.CompactTextString(m) }
func (*Telemetry) ProtoMessage()    {}
func (*Telemetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{0}
}

func (m *Telemetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telemetry.Unmarshal(m, b)
}
func (m *Telemetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telemetry.Marshal(b, m, deterministic)
}
func (m *Telemetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telemetry.Merge(m, src)
}
func (m *Telemetry) XXX_Size() int {
	return xxx_messageInfo_Telemetry.Size(m)
}
func (m *Telemetry) XXX_DiscardUnknown() {
	xxx_messageInfo_Telemetry.DiscardUnknown(m)
}

var xxx_messageInfo_Telemetry proto.InternalMessageInfo

func (m *Telemetry) GetType() Telemetry_Type {
	if m != nil {
		return m.Type
	}
	return Telemetry_ZERO
}

func (m *Telemetry) GetHello() *MsgHello {
	if m != nil {
		return m.Hello
	}
	return nil
}

func (m *Telemetry) GetAction() *MsgAction {
	if m != nil {
		return m.Action
	}
	return nil
}

type MsgHello struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHello) Reset()         { *m = MsgHello{} }
func (m *MsgHello) String() string { return proto.CompactTextString(m) }
func (*MsgHello) ProtoMessage()    {}
func (*MsgHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{1}
}

func (m *MsgHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHello.Unmarshal(m, b)
}
func (m *MsgHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHello.Marshal(b, m, deterministic)
}
func (m *MsgHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHello.Merge(m, src)
}
func (m *MsgHello) XXX_Size() int {
	return xxx_messageInfo_MsgHello.Size(m)
}
func (m *MsgHello) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHello.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHello proto.InternalMessageInfo

func (m *MsgHello) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *MsgHello) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type MsgAction struct {
	Type                 MsgAction_Action `protobuf:"varint,1,opt,name=type,proto3,enum=MsgAction_Action" json:"type,omitempty"`
	Pin                  uint32           `protobuf:"varint,2,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MsgAction) Reset()         { *m = MsgAction{} }
func (m *MsgAction) String() string { return proto.CompactTextString(m) }
func (*MsgAction) ProtoMessage()    {}
func (*MsgAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_93f6e686c665f83a, []int{2}
}

func (m *MsgAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAction.Unmarshal(m, b)
}
func (m *MsgAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAction.Marshal(b, m, deterministic)
}
func (m *MsgAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAction.Merge(m, src)
}
func (m *MsgAction) XXX_Size() int {
	return xxx_messageInfo_MsgAction.Size(m)
}
func (m *MsgAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAction proto.InternalMessageInfo

func (m *MsgAction) GetType() MsgAction_Action {
	if m != nil {
		return m.Type
	}
	return MsgAction_DIGITAL_LOW
}

func (m *MsgAction) GetPin() uint32 {
	if m != nil {
		return m.Pin
	}
	return 0
}

func init() {
	proto.RegisterEnum("Telemetry_Type", Telemetry_Type_name, Telemetry_Type_value)
	proto.RegisterEnum("MsgAction_Action", MsgAction_Action_name, MsgAction_Action_value)
	proto.RegisterType((*Telemetry)(nil), "Telemetry")
	proto.RegisterType((*MsgHello)(nil), "MsgHello")
	proto.RegisterType((*MsgAction)(nil), "MsgAction")
}

func init() { proto.RegisterFile("Telemetry.proto", fileDescriptor_93f6e686c665f83a) }

var fileDescriptor_93f6e686c665f83a = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x18, 0x85, 0x97, 0xae, 0xab, 0xed, 0xbf, 0xce, 0xc6, 0x80, 0x50, 0xbc, 0xd9, 0x88, 0x08, 0x03,
	0xa1, 0x17, 0xf3, 0xd2, 0x0b, 0xed, 0x74, 0xac, 0x85, 0x6a, 0x21, 0x14, 0x1c, 0xde, 0x94, 0x4d,
	0x82, 0x16, 0x6a, 0x1b, 0xbb, 0x22, 0xf4, 0x35, 0x7c, 0x14, 0x9f, 0x50, 0x92, 0xb6, 0x1b, 0xde,
	0xe5, 0x3f, 0xe7, 0xe4, 0xe4, 0xfb, 0x03, 0x4e, 0xc2, 0x73, 0xfe, 0xc9, 0xeb, 0xaa, 0xf1, 0x44,
	0x55, 0xd6, 0xe5, 0x85, 0x5d, 0x6c, 0x8b, 0x52, 0xec, 0xda, 0x89, 0xfe, 0x22, 0xb0, 0x0e, 0x09,
	0x72, 0x09, 0x7a, 0xdd, 0x08, 0xee, 0xa2, 0x19, 0x9a, 0x9f, 0x2e, 0x1c, 0xef, 0x78, 0x37, 0x69,
	0x04, 0x67, 0xca, 0x24, 0x53, 0x18, 0x7d, 0xf0, 0x3c, 0x2f, 0x5d, 0x6d, 0x86, 0xe6, 0xe3, 0x85,
	0xe5, 0x3d, 0xed, 0xdf, 0x03, 0x29, 0xb0, 0x56, 0x27, 0x14, 0x8c, 0xed, 0x5b, 0x9d, 0x95, 0x85,
	0x3b, 0x54, 0x09, 0x90, 0x09, 0x5f, 0x29, 0xac, 0x73, 0xe8, 0x2d, 0xe8, 0xb2, 0x92, 0x98, 0xa0,
	0xbf, 0xae, 0x58, 0x8c, 0x07, 0xc4, 0x06, 0x93, 0x6d, 0xd2, 0x60, 0x15, 0x45, 0x31, 0x46, 0x72,
	0x4a, 0xfa, 0x49, 0x23, 0x13, 0xb0, 0xd8, 0x26, 0xf5, 0x1f, 0x92, 0x30, 0x7e, 0xc6, 0x43, 0xba,
	0x04, 0xb3, 0x7f, 0x93, 0x9c, 0x83, 0x96, 0x09, 0x05, 0x6c, 0x2d, 0x47, 0x3f, 0x77, 0x9a, 0x89,
	0x99, 0x96, 0x09, 0x32, 0x85, 0x93, 0x6f, 0x5e, 0xed, 0x25, 0x84, 0xc4, 0x9c, 0xb4, 0xde, 0x3d,
	0xeb, 0x55, 0xfa, 0x05, 0xd6, 0x81, 0x8a, 0x5c, 0xfd, 0xdb, 0xfb, 0xec, 0xc8, 0xeb, 0x75, 0xd8,
	0xed, 0xe6, 0x18, 0x86, 0x22, 0xeb, 0x0a, 0x99, 0x3c, 0xd2, 0x6b, 0x30, 0xba, 0x0a, 0x07, 0xc6,
	0x8f, 0xe1, 0x3a, 0x4c, 0xfc, 0x28, 0x8d, 0xe2, 0x17, 0x3c, 0x20, 0x18, 0xec, 0x5e, 0x08, 0xc2,
	0x75, 0x80, 0xd1, 0xce, 0x50, 0x5f, 0x7e, 0xf3, 0x17, 0x00, 0x00, 0xff, 0xff, 0x75, 0xd1, 0x10,
	0x7a, 0x93, 0x01, 0x00, 0x00,
}
